### PR TITLE
Bintray Specs

### PR DESCRIPTION
**Pull request by jfryman**
This PR adds specs to the recently added BinTray feature #127, as it was running into some issues in real-world testing. This starts to close this gap.

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450225835014512

**Comment by jfryman** [comment]
:green_apple:

**Comment by lakshmi-kannan** [comment]
No donut! I don't see the repo in sources.list.d/stackstorm.list and the logs tell me we are trying to download the GPG key for downloads.stackstorm.net https://gist.github.com/lakshmi-kannan/fd7189df626a4a89c4b0

**Comment by lakshmi-kannan** [comment]
Heh. It looks like the hiera variable should be repo_base and not repo_root as per https://github.com/StackStorm/puppet-st2/pull/127 description. I caught that and re-ran installer with repo_base. Still no dice. https://gist.github.com/lakshmi-kannan/a609e0e2ce2c329b2709

**Comment by armab** [comment]
@lakshmi-kannan Sounds like different key?

I've just tried on clean Ubuntu14 VM.

```sh
add-apt-repository 'deb https://dl.bintray.com/stackstorm/trusty_staging unstable main'
apt-get update
...
Fetched 10.8 MB in 34s (314 kB/s)
Reading package lists... Done
W: GPG error: https://dl.bintray.com unstable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
```

After adding the key:
```sh
$ wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -
$ apt-get update
$ apt-get install st2api
...
# worked well
```

bintray@bintray.com key fingerprint for me is: 
```sh
$ apt-key finger

....
pub   4096R/D401AB61 2015-02-17
      Key fingerprint = 8756 C4F7 65C9 AC3C B6B8  5D62 379C E192 D401 AB61
uid                  Bintray (by JFrog) <bintray@bintray.com>
sub   4096R/DBE1D0A2 2015-02-17
```

`8756C4F765C9AC3CB6B85D62379CE192D401AB61`
Looks the same as listed here: https://bintray.com/docs/usermanual/uploads/uploads_gpgsigning.html

While I see you have: 
[A850304EED82AE89A136271F1AB74003483DED8B](/7fcdfac66c172318a6ae8645eaa8960755a2a13d/spec/classes/st2_package_debian_spec.rb#L37)

**Comment by jfryman** [comment]
@lakshmi-kannan heh. I guess you were right. I *never* have had a test pass on the first time properly.

Going to look at this after my doctors appt this AM.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450482727016366

**Pull request merged**
