### PR TITLE
Ubuntu Focal addition and Xenial  removal

### PR DESCRIPTION
**Pull request by rush-skills**
This PR prepares for the StackStorm v3.5 release adding some changes to drop 16.04 (Xenial) and add 20.04 (Focal).

- [x] Currently, the MongoDB version is set as 4.4 for all st2>3.4. Should this be replaced with only u20.04 getting mongo 4.4 and others 4.0?
- [x] Currently, StackStorm v3.5 is tested by pulling packages from the unstable channel. Should this first wait on the stable release?

### CODE REVIEW

**Comment by amanda11** [comment]
Thanks for all the work.

Yes - only use mongo 4.4 for Ubuntu 20 and st2 3.5 - to match other installers.

Also for 3.5 nodejs version 14 is required instead of 10.

**Comment by amanda11** [comment]
FYI - the 3.5.0 packages are now available in the stable packagecloud repo.

**Comment by rush-skills** [comment]
Thanks @amanda11 
> Yes - only use mongo 4.4 for Ubuntu 20 and st2 3.5 - to match other installers.
> Also for 3.5 nodejs version 14 is required instead of 10.

Sure, I will update the PR accordingly!

> FYI - the 3.5.0 packages are now available in the stable packagecloud repo.

Great, I will remove the references to unstable release testing.

**Comment by rush-skills** [comment]
Closing in favour of #335

**Pull request closed without merging**
