### PR TITLE
Remove duplicate http protocol from repo urls

### PR DESCRIPTION
**Pull request by DoriftoShoes**
I added a secondary http to the beginning of the protocol for some unexplainable reason last night.  This fixes that.

### CODE REVIEW

**Comment by Kami** [comment]
LGTM.

So this is the same as it was before the repo_protocol change, or?

**Comment by DoriftoShoes** [comment]
No, before the repo_protocol change the base url was hardcoded to downloads.stackstorm.net.  This PR makes it use whatever we pass in as base...so this is a fix for the original issue as well as the one I introduced last night...hahahaha.

**Comment by Kami** [comment]
Ah, OK, sounds good.

Is it possible to add some additional check which verifies that the repo_base passed in doesn't contain the protocol? This would make it safer and easier to spot similar issues in the fitire.

**Comment by lakshmi-kannan** [comment]
>Is it possible to add some additional check which verifies that the repo_base passed in doesn't contain the protocol? This would make it safer and easier to spot similar issues in the fitire.

@DoriftoShoes take this in another PR please. It's a valid comment.

**Comment by DoriftoShoes** [comment]
> @DoriftoShoes take this in another PR please. It's a valid comment.

Did you give me a Jira issue for this ;P

**Pull request merged**
