### PR TITLE
Updating requirements

### PR DESCRIPTION
**Pull request by bigmstone**
Updating requirements to move away from vulnerable versions of `rest-client`.

### CODE REVIEW

**Comment by nmaludy** [comment]
@bigmstone the CentOS 6 Gemfile has been archived, so we should be OK now. Not sure if we still get a warning on the repo or not?

**Comment by LindsayHill** [comment]
@nmaludy security warnings are gone now, so this probably no longer needed?

**Comment by nmaludy** [comment]
Awesome, closing. Please re-open if a warning pops up again.

**Comment by LindsayHill** [comment]
Actually sorry, that line is still there, it was just that the alert had been dismissed - https://github.com/StackStorm/puppet-st2/blob/master/build/centos6/Gemfile.lock#L61

**Pull request closed without merging**
