### PR TITLE
Puppet Lint fixes for the rest of the module

### PR DESCRIPTION
**Pull request by cryptk**
This PR fixes the remainder of the puppet-lint issues identified by the test system.

Now that the module can properly complete a profile::fullinstall on a clean 14.04 container, what are the odds of getting a new version of the module pushed to Puppet Forge?

### CODE REVIEW

**Comment by cryptk** [comment]
Actually, I think I found one last issue... On the initial run, puppet tries to start st2web before it installs the required files, so don't cut a new version to forge just yet...

**Comment by cryptk** [comment]
That last issue is addressed in #167

**Comment by nmaludy** [comment]
@cryptk a lot of work has been done to the repo lately with PR #172.

Can you please re-base and see if any of thee changes are still applicable?

Thanks,
Nick

**Comment by nmaludy** [comment]
Travis is showing that there are no puppet lint errors.

Closing this PR.

**Pull request closed without merging**
