### PR TITLE
Lets support dl-staging201

### PR DESCRIPTION
**Pull request by DoriftoShoes**
The current default on the repo_base case statement wouldn't work with dl-staging201...which makes staging break.  When staging breaks, I get sad.  When I get sad, I cry tears.  Unlike Bing Bong my tears aren't candy so it isn't pleasant.

### CODE REVIEW

**Comment by manasdk** [comment]
+1 just for the PR description

**Comment by Kami** [comment]
Just noticed a "new" failure:

```
\e[1;31mError: could not resolve http://http://dl-staging201/deb//pubkey.gpg\e[0m
\e[1;31mError: /Stage[main]/St2::Package::Debian/Apt::Source[stackstorm]/Apt::Key[Add key: 1E26DCC8B9D4E6FCB65CC22E40A96AE06B8C7982 from Apt::Source stackstorm]/Apt_key[Add key: 1E26DCC8B9D4E6FCB65CC22E40A96AE06B8C7982 from Apt::Source stackstorm]/ensure: change from absent to present failed: could not resolve http://http://dl-staging201/deb//pubkey.gpg\e[0m
```

It seems like we incorrectly specify `repo_base` value somewhere (probably in the datastore) and as such, it also includes protocol?

**Comment by Kami** [comment]
I just checked it, datastore looks fine, but it looks like `st2workroom_test` metadata file (`actions/st2workroom_test.meta.yaml) `dl_server` parameter includes protocol.

```
    dl_server:
      type: "string"
      default: "http://dl-staging201"
```

I will wait on @DoriftoShoes before making any changes, to make sure we are all on the same page and `repo_base` and `dl_server` not including a protocol is indeed what we want.

**Comment by DoriftoShoes** [comment]
This _should_ fix it: https://github.com/StackStorm/puppet-st2/pull/147

**Pull request merged**
